name: Build and upload Python wheels

on:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e #v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a

        name: Install Python
        with:
          python-version: '3.9'

      - name: Install python deps
        run: |
          python3 -m pip install gitpython wheel

      - name: Build and check dist
        run: |
          package_version="$(printf '%(%Y%m%d)T.${{ github.run_number }}')"
          echo "package_version=${package_version}" >> $GITHUB_ENV

          git_hash="$(git rev-parse HEAD)"
          echo "git_hash=${git_hash}" >> $GITHUB_ENV

          python build_tools/configure.py --use-pinned --add-version ${package_version}
          python setup.py sdist bdist_wheel
          ls -al dist/

      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.package_version }}
          release_name: iree-jax release at ${{ env.package_version }}
          body: |
            Automatic candidate release of iree-jax:
            https://github.com/google/iree-jax/commit/${{ env.git_hash }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@5bc3024cf83521df8ebfadf00ad0c4614fd59148 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: "${{ steps.create_release.outputs.id }}"
          assets_path: ./dist/iree_jax*.whl

      - name: Publish Release
        id: publish_release
        uses: eregon/publish-release@1128f16aff6272dc2132e2b5669948f1f488f02e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
