name: Test at head and bump pinned deps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  install_test:
    name: Install and Test
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a

        name: Install Python
        with:
          python-version: '3.9'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps
        run: |
          python3 -m pip install Filecheck lit flax

      - name: Run IREE-JAX Installation
        run: |
          python $GITHUB_WORKSPACE/build_tools/configure.py
          python3 -m pip install . -f https://iree-org.github.io/iree/pip-release-links.html --force-reinstall .[xla,cpu,test]

      - name: Run Tests
        run: |
          build_tools/unittest.sh

      - name: Update Pinned Versions
        run: |
          IREE_VERSION=$(python build_tools/update_pinned.py)
          cat version_info.json
          git config --local user.name "Bump Pinned Versions"
          git config --local user.email "iree-github-actions-bot@google.com"
          git commit -am "Update IREE to ${IREE_VERSION}"

      - name: Pushing changes
        run: |
          git push --force origin HEAD:update-pinned-versions

      - name: Posting to Discord
        uses: sarisia/actions-status-discord@c193626e5ce172002b8161e116aa897de7ab5383 # v1.10.2
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "iree-jax head bump failed"
          color: 0x0000ff
          username: GitHub Actions
