name: Test with pinned versions

on:
  workflow_dispatch:
  pull_request:

jobs:
  install_test:
    name: Install and Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # v2

        name: Install Python
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          python3 -m pip install Filecheck lit

      - name: Run installation
        run: |
          python $GITHUB_WORKSPACE/build_tools/configure.py --use-pinned
          python $GITHUB_WORKSPACE/build_tools/pip_install.py
      
      - name: Run tests
        run: |
          build_tools/unittest.sh

      # TODO: Once happy with the above commit any changes to pinned
      # version_info.json and push.
